[package]
name = "sac-jni"
version = "0.1.1"
license = "Apache-2.0"
edition = "2021"

[dependencies]
sac = { git = "https://github.com/SanmerDev/libsac.git", rev = "aeaf0d970d100743be408360d37a0d0e82d30890" }
jni = "0.21.1"

[lib]
name = "jni"
crate_type = ["cdylib"]
