[package]
name = "sac-jni"
version = "0.0.1"
license = "Apache-2.0"
edition = "2021"

[dependencies]
sac = { git = "https://github.com/SanmerDev/libsac.git", tag = "v0.1.3" }
jni = "0.21.1"

[lib]
name = "jni"
crate_type = ["cdylib"]
