[package]
name = "sac-jni"
version = "0.1.1"
license = "Apache-2.0"
edition = "2021"

[dependencies]
sac = { git = "https://github.com/SanmerDev/libsac.git", rev = "d58929c07e1606f5b6f73e7f4195197a078f3705" }
jni = "0.21.1"

[lib]
name = "jni"
crate_type = ["cdylib"]
