[package]
name = "sac-jni"
version = "0.1.1"
license = "Apache-2.0"
edition = "2021"

[dependencies]
sac = { git = "https://github.com/SanmerDev/libsac.git" }
jni = "0.21.1"

[lib]
name = "sac_jni"
crate_type = ["cdylib"]
